### ISSUE TITLE
uiux: not intuitive when finished challenge show up in past challenges and displayed as disabled button

### ISSUE THREAD

**Issue by ryanycw** [AlibudaLab/atomic-habit-builder#148]
![image](https://github.com/user-attachments/assets/815bbb76-7bf7-4e78-8f86-845529a26b08)

**Comment by cc03668** [comment]
![Image](https://github.com/user-attachments/assets/fd8b3cca-5b1d-4846-8105-899128b63a61)



![Image](https://github.com/user-attachments/assets/9414dddb-a96e-4706-8f44-3d9402008c6e)
