### ISSUE TITLE
uiux: 顯示其他挑戰者進度

### ISSUE THREAD

**Issue by antoncoding** [AlibudaLab/atomic-habit-builder#166]
# Description

我會想在挑戰的頁面看到其他人挑戰的進度。我認爲看到其他人的進度，可以增加我完成的動機

舉例來說：參加者 A，完成次數 1/5

proposed by @Ankarrr

**Comment by cc03668** [comment]
1. 每一個挑戰的 leader board

**Comment by cc03668** [comment]
![Image](https://github.com/user-attachments/assets/0e96df1a-c532-4e51-af2e-16f4f31375a7)

**Comment by ryanycw** [comment]
@Ankarrr 

1. Just add the following in `web/app/api/on-chain/challenges/route.ts` 
<img width="469" alt="image" src="https://github.com/user-attachments/assets/07b9d782-ce68-4259-be4a-7c88a62d2b9d">

2. Adjust return here to include joinedUsers and checkIns
https://github.com/AlibudaLab/atomic-habit-builder/blob/7f681ff3ba307ce9f334202d52659cd2a1386c9a/web/src/providers/ChallengesProvider.tsx#L76
