### ISSUE TITLE
leaderboard check in 完成後不會馬上更新

### ISSUE THREAD

**Issue by Ankarrr** [AlibudaLab/atomic-habit-builder#210]
# 問題
leaderboard 在 check in 完以後不會馬上更新 😱 因為現在是開 app 才會更新一次

# 解法
1. 最簡單的 refetch 會導致跳出到其他 challenge
2. 可能要把拉 leaderboard 放到另一個 hook 作，這樣就可以 partial update

graph 那邊 index 速度是技術上的限制，約有 2s 的 delay

# 新版解法 

1. 增加一個 reload button
2. wait 2s 之後再次 refetch

我認爲 1. 是必須要做，因為 2 是不完全可靠，2s 只是我們估算的值

**Comment by Ankarrr** [comment]
在 ActivityCheckIn.tsx 的 `useCheckInRun()` 的 OnSuccess 看起來已經會 refetch
```
      Promise.all([refetchAll()]).catch((error) => {
        console.error('Error refetching data:', error);
        // Optionally, handle the error more specifically here
      });
```
所以我不確定為什麼 leaderboard 沒更新。可能 graph index 還是需要一點時間？

而看到資料沒更新，用戶常見的行為是下拉更新。所以我提議增加下拉更新功能，如此就算沒有 checkIn 成功當下沒有抓到新的資料，用戶還是可以主動再 refetch。這樣如何？

**Comment by antoncoding** [comment]
solution: 加一個 refresh button

**Comment by Ankarrr** [comment]
流程：
1. 發送 checkIn 請求
2. zerodev 發出交易
3. 交易上鏈
4. app refetch -> 目前會在這個步驟 refetch
5. graphql index 到交易 -> 這個步驟會 delay
6. app refetch -> 要改成在這個步驟 refetch
7. 資料更新
