### ISSUE TITLE
feat: better way to share to farcaster

### ISSUE THREAD

**Issue by antoncoding** [AlibudaLab/atomic-habit-builder#84]
## Objective

* research how to make the "shared post" more attractive
  *  縮圖, challenge specific description?

**Comment by cc03668** [comment]
@ryanycw 研究如何把 Strava 的路徑圖、運動數據下載下來，加進 farcaster 的分享內容

**Comment by ryanycw** [comment]
@cc03668 will finish the design and this ticket will be implemented in https://github.com/AlibudaLab/atomic-habit-builder/pull/189
